ASP_WebCam/Models/RobotModel.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;

namespace ASP_WebCam.Models
{
    public class RobotModel
    {

        public int Counter { get; set; }
        public string Start { get; set; }
        public string ChangeText = "What";
        public Image MyBitImage { get; set; }
        public string MyImagePath { get; set; }
        public byte[] ImageBytes { get; set; }

    }

    
}

ASP_WebCam/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP_WebCam.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ASP_WebCam/Controllers/RobotController.cs
using ASP_WebCam.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AForge.Video;
using AForge.Video.DirectShow;
using System.Drawing;

namespace ASP_WebCam.Controllers
{
    public class RobotController : Controller
    {

        private FilterInfoCollection webcam = new FilterInfoCollection(FilterCategory.VideoInputDevice);
        private VideoCaptureDevice cam;

        public ActionResult Webcam()
        {
            cam = new VideoCaptureDevice(webcam[0].MonikerString);
            cam.NewFrame += new NewFrameEventHandler(cam_NewFrame);
            cam.Start();
            return View("Index");
        }

        
        void cam_NewFrame(object sender, NewFrameEventArgs eventArgs)
        {
            Bitmap bit;
            bit = (Bitmap)eventArgs.Frame.Clone();
           
            VideoInput cc;
            //cc=(VideoInput)eventArgs.Frame.Clone();
            MyLoad(bit);

        }

        public ActionResult MyLoad(Bitmap bit_map)
        {
           
            RobotModel nn = new RobotModel() { MyBitImage = bit_map };
            ViewBag.WHY = (byte[])new ImageConverter().ConvertTo(nn.MyBitImage, typeof(byte[]));
            //ViewBag.Vid = c;
            return View(nn);
        }

        
        // GET: Robot
        public ActionResult Index()
        {
            Webcam();
            return View();
        }

    }
}

ASP_WebCam/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ASP_WebCam/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ASP_WebCam/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ASP_WebCam/Views/Robot/Index.cshtml
@model ASP_WebCam.Models.RobotModel

@{
    ViewBag.Title = "Index";
}



<div class="row">


    <div class="col-md-6">
        @{ try
            {
                <p>@ViewBag.WHY</p>
                <video width="320" height="240" controls>
                    <source src=ViewBag.Vid type="video/mp4">
                
                </video>
                <img src="@String.Format("data:image/jpg;base64,{0}", Convert.ToBase64String(ViewBag.WHY))" />
                <p>This is working</p>
            }
            catch
            {
                <img src="~/Content/image.jpg" width="500" height="330" />
                <p>This is not working</p>
            }

        }
        
        
    </div>
</div>

<div class="row">
   
    <div class="col-md-2">

        @using (Html.BeginForm("Webcam", "Robot"))
        {
            <input id="buttonWebcam" type="submit" name="webcame" value="Webcam" />
        }
    </div>
</div>

ASP_WebCam/Views/Robot/Start.cshtml
@model ASP_WebCam.Models.RobotModel

@{
    ViewBag.Title = "Start";
}

<h2>@Model.Start</h2>

ASP_WebCam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Robot Page", "Index", "Robot")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>